[package]
name = "gds21"
version = "0.1.0"
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"

[dependencies]
derive_builder = "0.9.0"
byteorder = "1.3.4"
num-traits = "0.2"
num-derive = "0.3"
