[package]
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
name = "gds21"
version = "0.1.0"
repository = "https://github.com/dan-fritchman/Layout21"

[dependencies]
byteorder = "1.3.4"
derive_builder = "0.9.0"
enum_dispatch = "0.3.1"
num-derive = "0.3"
num-traits = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0.88"
serde_json = "1.0"
serde_yaml = "0.8"
tempfile = {version = "3", optional = true}
toml = "0.5.7"
chrono = {version = "0.4", features = ["serde"]}

[dev-dependencies]
tempfile = {version = "3"}

[features]
selftest = ["tempfile"]
