[package]
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
name = "layout21"
version = "0.1.0"

[dependencies]
gds21 = {package = "gds21", version = "0.1.0", path = "../gds21"}
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0.88"
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.5.7"
slotmap = { version = "1.0", features = ["serde"] }
