[package]
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
name = "layout21"
version = "0.1.0"

[dependencies]
layout21raw = {package = "layout21raw", version = "0.1.0", path = "../layout21raw"}
enum_dispatch = "0.3.1"
num-integer = "0.1"
num-traits = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0.88"
serde_json = "1.0"
serde_yaml = "0.8"
slotmap = {version = "1.0", features = ["serde"]}
toml = "0.5.7"
derive_more = "0.99.16"
