[package]
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
name = "layout21raw"
version = "0.1.0"

[dependencies]
# Local workspace dependencies
gds21 = {path = "../gds21", optional = true}
layout21protos = {path = "../layout21protos", optional = true}
lef21 = {path = "../lef21", optional = true}
# Crates.io 
enum_dispatch = "0.3.7"
num-integer = "0.1"
num-traits = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0.88"
serde_json = "1.0"
serde_yaml = "0.8"
slotmap = {version = "1.0", features = ["serde"]}
toml = "0.5.7"

[features]
default = ["gds", "lef", "proto"]
gds = ["gds21"]
lef = ["lef21"]
proto = ["layout21protos"]
