[package]
authors = ["Dan Fritchman <dan@fritch.mn>"]
edition = "2018"
name = "layout21"
version = "0.1.0"
workspace = "../"

[dependencies]
# Local workspace dependencies
layout21raw = {path = "../layout21raw"}
layout21utils = {path = "../layout21utils"}
# Crates.io 
derive_more = "0.99.16"
enum_dispatch = "0.3.1"
num-integer = "0.1"
num-traits = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0.88"
serde_json = "1.0"
serde_yaml = "0.8"
slotmap = {version = "1.0", features = ["serde"]}
toml = "0.5.7"
