#
# # Dependency Audits & Checks
#

- name: cargo-audit
  uses: actions-rs/audit-check@v1.2.0
  continue-on-error: true

- name: cargo-deny
  uses: EmbarkStudios/cargo-deny-action@v1.2.1
  continue-on-error: true

- name: cargo-deny2
  on: [push, pull_request]
  jobs:
    cargo-deny:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          checks:
            - advisories
            - bans licenses sources

      # Prevent sudden announcement of a new advisory from failing ci:
      continue-on-error: true ## ${{ matrix.checks == 'advisories' }}

      steps:
        - uses: actions/checkout@v2
        - uses: EmbarkStudios/cargo-deny-action@v1
          with:
            command: check ${{ matrix.checks }}
